insert into Posts (title, body, user_id) values ('Lucky Jordan', 'sagittis sapien cum sociis natoque penatibus et magnis dis parturient', 3);
insert into Posts (title, body, user_id) values ('Starter for 10', 'posuere cubilia curae nulla dapibus dolor vel est donec odio', 2);
insert into Posts (title, body, user_id) values ('Public Housing', 'sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique', 2);
insert into Posts (title, body, user_id) values ('King of California', 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis', 1);
insert into Posts (title, body, user_id) values ('Age of Stupid, The', 'sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi', 3);
insert into Posts (title, body, user_id) values ('Stupids, The', 'eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero', 3);
insert into Posts (title, body, user_id) values ('Divide, The', 'et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', 2);
insert into Posts (title, body, user_id) values ('Amistad', 'lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh', 2);
insert into Posts (title, body, user_id) values ('Dead Man and Being Happy, The (El muerto y ser feliz)', 'posuere metus vitae ipsum aliquam non mauris morbi non lectus', 2);
insert into Posts (title, body, user_id) values ('Earth Entranced (Terra em Transe)', 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', 2);
