insert into Posts (title, body, post_details_id) values ('Leap Year (Año bisiesto)', 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae', 6);
insert into Posts (title, body, post_details_id) values ('Song of the Thin Man', 'iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla', 3);
insert into Posts (title, body, post_details_id) values ('Quadrille', 'primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae', 1);
insert into Posts (title, body, post_details_id) values ('Let''s Get Harry', 'sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique', 2);
insert into Posts (title, body, post_details_id) values ('Gun Crazy (a.k.a. Deadly Is the Female)', 'cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis', 2);
insert into Posts (title, body, post_details_id) values ('Beloved/Friend (a.k.a. Amigo/Amado) (Amic/Amat)', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada', 1);
insert into Posts (title, body, post_details_id) values ('Enter the Phoenix (Da lao ai mei li)', 'justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio', 6);
insert into Posts (title, body, post_details_id) values ('Nighthawks', 'id consequat in consequat ut nulla sed accumsan felis ut at dolor quis', 8);
insert into Posts (title, body, post_details_id) values ('Unsuspected, The', 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla', 9);
insert into Posts (title, body, post_details_id) values ('Clockwatchers', 'amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 4);
